### ISSUE TITLE
W3S Discord submission message grammar mistakes

### ISSUE THREAD

**Issue by Original-Developer** [H1Mohamed/Scary-Life-Organizer#1]
### Consider fixing the few following grammar mistakes from the message you posted on W3S Discord Server:
![2022-10-30_12-02](https://user-images.githubusercontent.com/113319174/198875888-0896d598-5f93-4cd3-a9de-2df75c3a0c33.png)
- **Subission:** It's "Submission"
- **Extention:** It's "Extension"
- **Callender:** It's "Calendar"
- **StopWatch:** You probably meant "CountDown"; StopWatchs are a different thing
- **Orginizer:** It's "Organizer"
- **Tecnologeis:** It's "Technologies"

**Comment by H1Mohamed** [comment]
thanx for the help,did you notis any mestakes in the readme.md ?

**Comment by H1Mohamed** [comment]
btw I realy want you to use the extension and see if it has a stopwatch or a timer.
